version: '1'
services:
  postgresql:
    image: postgres:17
    command: postgres -c 'max_connections=100'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: library
  redis:
    image: redis:latest
    command: redis-server --requirepass redis_password
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: redis_password
#  mongo:
#    image: mongo:latest
#    ports:
#      - "27017:27017"
